pipeline:
  name: harness-demo
  identifier: harnessdemo
  projectIdentifier: devops001
  orgIdentifier: TCS
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: sddemogit
        repoName: kube-harness-demo
        build: <+input>
  stages:
    - stage:
        name: imagebuild
        identifier: imagebuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessdemo
              namespace: harness-demo
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: sddemo
                    repo: mail2sandeepd/harness-demo
                    tags:
                      - sd-v2
    - stage:
        name: demo-deploy
        identifier: demodeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: sdhelmsvc
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  variables:
                    - name: NAMESPACE
                      type: String
                      value: <+input>
          environment:
            environmentRef: harnessdemoenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessdemoinfra
                inputs:
                  identifier: harnessdemoinfra
                  type: KubernetesDirect
                  spec:
                    namespace: <+input>
          execution:
            steps:
              - step:
                  type: HelmDeploy
                  name: HelmDeploy_1
                  identifier: HelmDeploy_1
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
