pipeline:
  name: harness-demo
  identifier: harnessdemo
  projectIdentifier: devops001
  orgIdentifier: TCS
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: sddemogit
        repoName: kube-harness-demo
        build: <+input>
  stages:
    - stage:
        name: imagebuild
        identifier: imagebuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessdemo
              namespace: harness-demo
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: mail2sandeepd/harness-demo
                    tags:
                      - sd-v2
